#!/usr/bin/env bash
# fizz buzz
numbers=1
while [ "$numbers" -lt 101 ]
do
if [ $((numbers%15)) = 0 ]
then echo "FizzBuzz"
elif [ $((numbers%3)) = 0 ]
then
echo "Fizz"
elif [ $((numbers%5)) = 0 ]
then
echo "Buzz"
else 
echo "$numbers"
fi
((numbers++))
done
