#!/usr/bin/env bash
#manage process
FILE="/var/run/my_process.pid"

function error()
{
    echo "Usage: manage_my_process {start|stop|restart}"
}

function start()
{
    (./manage_my_process) &
    echo $$ > $FILE
    echo "manage_my_process started"
}

function stop()
{
    pkill -f ./manage_my_process
     
    echo "manage_my_process stopped"
	rm $FILE
	echo "Good"
}

function restart()
{
    pkill -f ./manage_my_process
    rm $FILE
    ./manage_my_process &
    echo $$ > $FILE
    echo "manage_my_process restarted"
}

if [ $# -ne 1 ];
then
    error
else
    case ${1} in
    	"start")
    	    start;;
    	"restart")
    	    restart;;
    	"stop")
    	    stop;;
    	*)
    	    error;;
    esac
fi
